[tox]
requires =
    tox>=4.2
env_list =
    pre-commit
    BOM

[testenv]
package = wheel
wheel_build_env = .pkg
constrain_package_deps = true
uv_python_preference = only-managed

[testenv:pre-commit]
description = pre-commit checks and fixes
skip_install = true
commands =
    pre-commit run --all-files --hook-stage=manual --show-diff-on-failure
allowlist_externals =
    pre-commit

[testenv:BOM]
description = generate the software bill of materials
skip_install = true
commands =
    mkdir -p BOM/
    reuse spdx -o BOM/project_licenses.spdx
allowlist_externals =
    mkdir
    reuse

[testenv:test]
description = pre-commit checks and fixes
skip_install = true
commands =
    rm --recursive --force test-gen
    mkdir --parent test-gen/test-1
    copier copy --trust --force --vcs-ref HEAD . test-gen/test-1 \
      --data project_name="Whiteprint Test" \
      --data author="Romain Brault" \
      --data organisation="RomainBrault" \
      --data author_email="mail@romainbrault.com" \
      --data code_license_id="MIT-0" \
      --data resources_license_id="CC0-1.0" \
      --data copyright_holder="Romain Brault" \
      --data copyright_holder_email="mail@romainbrault.com" \
      --data line_length="79" \
      --data target_python_version="3.10"
allowlist_externals =
    copier
    mkdir
    rm
