ARG UV_COMPILE_BYTECODE=1
ARG PYTHONDONTWRITEBYTECODE=1
ARG PYTHONUNBUFFERED=1
ARG TAG=3.13.3-alpine3.20@sha256:40a4559d3d6b2117b1fbe426f17d55b9100fa40609733a1d0c3f39e2151d4b33

ARG VIRTUAL_ENV=/opt/venv

# Use a multi-stage build to reduce the size of the final image.
#   This example is optimized to reduce final image size rather than for
#   simplicity.
# Using a -slim image also greatly reduces image size.
# It is possible to use -alpine images instead to further reduce image size,
# but this comes with several important caveats.
#   - Alpine images use MUSL rather than GLIBC (as used in the default
#   Debian-based images).
#   - Most Python packages that require C code are tested against GLIBC, so
#   there could be subtle errors when using MUSL.
#   - These Python packages usually only provide binary wheels for GLIBC, so
#   the packages will need to be recompiled fully within the container images,
#   increasing build times.
ARG UV_TAG=0.7.14@sha256:cda0fdc9b6066975ba4c791597870d18bc3a441dfc18ab24c5e888c16e15780c
ARG UV_BIN="/usr/local/bin"

FROM ghcr.io/astral-sh/uv:${UV_TAG} AS uv_image

ARG TAG

FROM docker.io/python:${TAG} AS python_builder

# Install any system dependencies required to build wheels, such as C
# compilers or system packages For example:
RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    apk add --update git

ARG UV_BIN

COPY --from=uv_image /uv ${UV_BIN}/uv

ARG UV_COMPILE_BYTECODE
ARG PYTHONDONTWRITEBYTECODE
ARG PYTHONUNBUFFERED
ARG VIRTUAL_ENV

ENV UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=never \
    UV_PROJECT_ENVIRONMENT=${VIRTUAL_ENV}
RUN ${UV_BIN}/uv venv \
        --python="/usr/local/bin/python" \
        --relocatable \
        ${VIRTUAL_ENV}

# Copy in project dependency specification.
ARG WORKDIR=/src
WORKDIR ${WORKDIR}

# Install the project dependencies
COPY pyproject.toml *.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    set -ex && \
    ${UV_BIN}/uv export \
        --python="${VIRTUAL_ENV}/bin/python" \
        --format="requirements-txt" \
        --output-file requirements.txt \
        --all-extras \
        --frozen \
        --no-dev \
        --no-emit-project && \
    ${UV_BIN}/uv pip install \
        --python="${VIRTUAL_ENV}/bin/python" \
        --require-hashes \
        --verify-hashes \
        --no-break-system-packages \
        --requirement requirements.txt

# Copy in source files.
COPY README.md hatch.toml hatch_build.py ./
COPY LICENSES LICENSES/
COPY src src/
COPY .git .git/

# Manually build/install the package.
RUN --mount=type=cache,target=/root/.cache/uv \
    set -ex && \
    ${UV_BIN}/uv pip install \
        --python="${VIRTUAL_ENV}/bin/python" \
        --no-cache \
        --no-break-system-packages \
        --no-deps \
        .

## Final Image
# The image used in the final image MUST match exactly to the python_builder
# image.
FROM docker.io/python:${TAG} AS python_runner

# For Python applications that are not installable libraries, you may need to
# copy in source files here in the final image rather than in the
# python_builder image.

# Copy and activate pre-built virtual environment.
ARG VIRTUAL_ENV
COPY --from=python_builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"

# Give access to the entire home folder to the new user so that files and
# folders can be written there. Some packages such as matplotlib, want to write
# to the home folder.
USER nobody

ARG HOME="/app"
ENV HOME=${HOME}
WORKDIR ${HOME}

ARG PYTHONDONTWRITEBYTECODE
ARG PYTHONUNBUFFERED
ENV PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE} \
    PYTHONUNBUFFERED=${PYTHONUNBUFFERED}

ENTRYPOINT ["python"]

ARG PYTHON_VERSION
ARG BASE_OS
ARG DIGEST
ARG BUILD_DATE
ARG VERSION
ARG REVISION
ARG TAG

LABEL org.opencontainers.image.authors='{{ author }} <{{ author_email }}>' \
      org.opencontainers.image.documentation='' \
      org.opencontainers.image.source='' \
      org.opencontainers.image.description='{{ description }}' \
      org.opencontainers.image.vendor='{{ organisation }}' \
      org.opencontainers.image.licenses='{{ code_license_id }}' \
      org.opencontainers.image.version=${VERSION} \
      org.opencontainers.image.revision=${REVISION} \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.title='{{ package_name }}' \
      org.opencontainers.image.description='{{ description }}' \
      org.opencontainers.image.ref.name=${TAG} \
      org.opencontainers.image.base.name='docker.io/python:'${TAG}
